Modified for start without --privileges key

diff --git a/bin/pptpd_init b/bin/pptpd_init
--- a/bin/pptpd_init
+++ b/bin/pptpd_init
@@ -3,10 +3,14 @@
 set -e
 
 # enable IP forwarding
-sysctl -w net.ipv4.ip_forward=1
-echo "IPv4 forwarding enabled"
+if [[ $(sysctl -n net.ipv4.ip_forward) -eq 0 ]]; then
+    echo "Enabling IPv4 Forwarding"
+    # If this fails, ensure the docker container is run with --privileged
+    sysctl -w net.ipv4.ip_forward=1 || echo "Failed to enable IPv4 Forwarding"
+fi
 
 # configure firewall
+echo "Configuring iptables"
 set -x
 iptables -t nat -A POSTROUTING -s ${SUBNET} ! -d ${SUBNET} -j MASQUERADE
 iptables -A FORWARD -s ${SUBNET} -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j TCPMSS --set-mss 1356
@@ -14,13 +18,12 @@ iptables -A INPUT -i ppp0 -j ACCEPT
 iptables -A OUTPUT -o ppp0 -j ACCEPT
 iptables -A FORWARD -i ppp0 -j ACCEPT
 iptables -A FORWARD -o ppp0 -j ACCEPT
-set +x
-echo "The iptables configured"
+{ set +x ;} 2> /dev/null
 
 # configure pptp IP address ranges
 sed -i "s/^localip.*/localip ${LOCAL_IP}/" /etc/pptpd.conf
 sed -i "s/^remoteip.*/remoteip ${REMOTE_IP}/" /etc/pptpd.conf
-echo -e "Local ip: \t${LOCAL_IP}\nRemote ip: \t${REMOTE_IP}"
+echo -e "\nLocal ip: \t${LOCAL_IP}\nRemote ip: \t${REMOTE_IP}"
 
 # configure pptp user
 if [ x"${USER}" != "x" -a x"${PASS}" != "x" ]; then
@@ -32,7 +35,8 @@ if [ x"${USER}" != "x" -a x"${PASS}" != "x" ]; then
     fi
 fi
 
-echo "Configuration:"
+echo -e "\n## PPTPD configuration ##"
 cat /etc/ppp/options.pptp
+echo -e "#########################\n"
 
 exec "$@"
